### ISSUE TITLE
slow to open

### ISSUE THREAD

**Issue by seiyria** [farin99/angular2-virtual-select#1]
hey! nice work on this so far. I just picked it up today and compared to ng2-select, it works a lot better for my dataset (2500+ items).

I'm having an issue where my select opens a bit slowly. You can see it [on the demo page](http://angular2-virtual-select.s3-website-us-east-1.amazonaws.com/) as well, if you hit "object array single select" it takes a bit.

Is there any way to speed this up?

**Comment by farin99** [comment]
Thanks @seiyria, I see the delay. I will try to check what is causing it.

**Comment by farin99** [comment]
Ok, after investigating it, I saw that angular2-highlight-js was taking a long time to execute every time you open\close the menu. looking inside the package code, I saw it is re-evaluating the code block in "ngAfterViewChecked" - this means that it will be called a lot even if the code block didn't change.

I created my own wrapper for highlight js and now everything is working fast! 
I moved the demo page to a [githup page](https://farin99.github.io//demos) you can check it out there.

So this was the reason the demo page was a bit slow, I'm guessing there is something else going on in your app.

**Comment by seiyria** [comment]
Thanks for getting back to me. Strangely, mine are opening faster now and I'm not sure why. I had an `*ngIf` on them preventing them from rendering in certain cases but after taking it away it seems to load instantly. I did find another bug though which I'll open up an issue for. If it's resolved on your end feel free to close it.

**Comment by farin99** [comment]
Awesome, thanks!
