### ISSUE TITLE
How to change the default style of the component?

### ISSUE THREAD

**Issue by alismart** [farin99/angular2-virtual-select#13]
when trying to add bootstrap .form-control class, the style goes wrong. since the component is less in height than the form-control boarders. any solution?

**Comment by farin99** [comment]
Not sure why you need this class, as sh-select already provide the style (like the border and expand to 100% width etc) for you.
If you still want it, you can just override the .form-control border to make it look OK:
`<sh-select [options]="['aaaa','bbbb']" class="form-control" style="border: none"></sh-select>`

**Comment by farin99** [comment]
Closing as answered
