### ISSUE TITLE
scrolling in a list that's too large hides some items when grabbing by the scroll cursor

### ISSUE THREAD

**Issue by seiyria** [farin99/angular2-virtual-select#2]
By scroll cursor, I mean the thing on the right between the arrows.

You can see here the result of this (notice the empty space below everything, but the cursor is at the bottom):

![image](https://cloud.githubusercontent.com/assets/763609/22333962/a6f6e622-e3a6-11e6-83b9-59f507f361a1.png)

Basically, if you grab that and drag it around in a list of items that's ~2500 plus, you see some wonky behavior. Sometimes there are empty spaces, sometimes the cursor jitters. I'm not sure how to explain it besides that. If it's hard to replicate I can probably throw together a demo.

**Comment by farin99** [comment]
I was able to reproduce the issue. From what I see it will happen when in the visible items you will have items with different heights (e.g, in the same viewport both a one liner and two line).
As a quick fix, I will force nowrap. You will have a horizontal scroll instead.
