### ISSUE TITLE
clear icon does not show up

### ISSUE THREAD

**Issue by seiyria** [farin99/angular2-virtual-select#3]
I just noticed that it appears in my DOM but I can't actually see it. I suspect that `.icon.clear` is from some icon framework but I can't tell which.

**Comment by seiyria** [comment]
This can be fixed by doing:

`i.close.icon.clear::after { content: "\d7" }`

**Comment by farin99** [comment]
it was from semantic ui :). Off curse you are right and it should be independent. I like your solution and will add it.Thanks!

**Comment by farin99** [comment]
fixed by 3e7ff7a
