### ISSUE TITLE
selecting a value does not clear the internal input

### ISSUE THREAD

**Issue by seiyria** [farin99/angular2-virtual-select#6]
Probably, `clear` can just call `updateFilter('')` but I'm not too sure.

**Comment by farin99** [comment]
This makes perfect sense for single mode. I am conflicted about multiple select mode. 
Perhaps the correct way will be to clear the filter every time the menu closes.

**Comment by seiyria** [comment]
Maybe. I think it's a bit jarring, because when I would do a multi select with anything I would type, arrow, enter, then start typing again (expecting it to be cleared).

Either way, this isn't a _huge_ deal in either regard, but it is an oddity so I mentioned it.

**Comment by farin99** [comment]
Clearing the filter for both select and multi-select every selection or menu closes
