### ISSUE TITLE
set default value

### ISSUE THREAD

**Issue by seiyria** [farin99/angular2-virtual-select#8]
I think right now, the value is represented as the object given instead of the `key` which is problematic. If you want to use this when, for example, editing data you'd need to formulate an object (and even then I'm not sure if it would work due to object references). That being the case, it would be ideal if I could pass in `[value]="myKeyValue"` and have it recognize that as the current value when initializing the select (you could coerce this to an array in a setter).

Logistically I'm not sure how this would work though, unfortunately.

**Comment by farin99** [comment]
Just to make sure I understand, you are passing an array of objects to "options" and would like to have some of them already selected?

If so, this isn't good enough?

Multiselect:
```
<sh-select [options]="options" 
           [(ngMode)l]="selected"
           [isMultiselect]="true"></sh-select>
```

Single:
```
<sh-select [options]="options" 
           [(ngModel)]="selected"
           [isMultiselect]="true"></sh-select>
```

And somthing like this in your ts file
```
this.options=[{name:"a"},{name:"b"}];
this.selected = [this.options[0]];
```

**Comment by seiyria** [comment]
Hm. Can you set the ngModel? I was certain I'd tried that but I must not have. If so, that'd be fine, I think, as long as it does deep compares and doesn't rely on object references. I'll report back in a bit.

**Comment by farin99** [comment]
It isn't deep compared, so it won't work if you are not setting the same object as in the options array. 
For editing - duplicate the object and on saved update the original one isn't an option?

**Comment by seiyria** [comment]
This may work. I actually have a wrapper around sh-select so I have to do some weird stuff. But I do have access to the array as well in my wrapper so I'm just going to pass in the value, find the option, and set the value when the select loads. I'll close this for now since it seems to be implemented, I just couldn't comprehend it at the time of posting. Turns out it's in the readme too, I was digging into the code.
