### ISSUE TITLE
SystemJS Error "Not Found"

### ISSUE THREAD

**Issue by johnhenriksson** [farin99/angular2-virtual-select#9]
I'm getting a SystemJS error. How should i add angular2-virtual-select in the systemjs file?

`Error: XHR error (404 Not Found) loading http://localhost:3000/angular2-virtual-select `

**Comment by farin99** [comment]
Use:
import {ShSelectModule} from "angular2-virtual-select/dist/index";

**Comment by johnhenriksson** [comment]
I'm setting this in my app.module but I'm still getting this error:

`Error: XHR error (404 Not Found) loading http://localhost:3000/angular2-virtual-select/dist/index`

Angular v2.4.0

**Comment by farin99** [comment]
Hm. I tried to reproduce it with angular-seed and everything seems to be working fine.
Can you please share a tester that reproduces the issue

Also, can you please make sure you are using the latest version and using the module with:
ShSelectModule.forRoot()

**Comment by farin99** [comment]
As it is working with the angular-seed project, I'm closing the issue.
If you are still having issues please share more information.
